---
title: "SISG Module 17: Computational Pipeline for WGS Data"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: UW-GAC/SISG_2019
description: "Course materials for SISG Module 17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE)
```

# Introduction

This site contains course materials for Course materials for SISG Module 17: Computational Pipeline for WGS Data, July 24-26, 2019.
Data used is located in the [github repository](https://github.com/UW-GAC/SISG_2019) from which the site is built, as well as in the [TOPMed analysis pipeline](https://github.com/UW-GAC/analysis_pipeline).

To work through the exercises, log into http://bit.ly/datastage-sb with your username and password.

Slides for lectures are linked below in the schedule. A detailed description of the course and instructor biographies can be found at https://www.biostat.washington.edu/suminst/SISG2019/modules/SM1917

Join the Slack channel here:
https://sisg2019module17.slack.com ([link to sign up](https://join.slack.com/t/sisg2019module17/signup))

## Schedule

**Wednesday, July 24**

- [Introduction](https://www.biostat.washington.edu/sites/default/files/modules/SISGmod17Intro_v2.pdf)
    - [Setup for interactive exercises](https://www.biostat.washington.edu/sites/default/files/modules/SISG19_Scaling_WGS_Association_Studies_in_the_Cloud_with_Seven_Bridges.pdf) (Part 1)
- Sequencing data formats
    - [Sequencing data formats](https://www.biostat.washington.edu/sites/default/files/modules/Sequencing_data_formats.pdf)
    - [Intro to Genomic Data Storage](https://www.biostat.washington.edu/sites/default/files/modules/GDS_intro_0.pdf)
    - [Exercises](https://uw-gac.github.io/SISG_2019/gds-format.html)
- [Phenotype harmonization](https://www.biostat.washington.edu/sites/default/files/modules/sisg_2019_m17_pheno_harmonization.pdf)
    - [Exercises](https://uw-gac.github.io/SISG_2019/phenotype-harmonization.html)
- Association tests
    - [Methods and motivation](https://www.biostat.washington.edu/sites/default/files/modules/SISGAssocTests19WGSmodule.pdf) (Part 1)

**Thursday, July 25**

- Association tests
    - [Methods and motivation](https://www.biostat.washington.edu/sites/default/files/modules/SISGAssocTests19WGSmodule.pdf) (Part 2)
    - [GENESIS for association tests](https://www.biostat.washington.edu/sites/default/files/modules/R_assoc_tests_0.pdf)
    - [Exercises](https://uw-gac.github.io/SISG_2019/association-tests.html)
    - [Aggregate tests](https://www.biostat.washington.edu/sites/default/files/modules/SISGAssocTests19WGSmodule.pdf) (Part 3)
    - [Exercises](https://uw-gac.github.io/SISG_2019/association-tests.html#sliding-window-tests)
- Population structure and relatedness
    - [Population structure inference](https://www.biostat.washington.edu/sites/default/files/modules/Population_Structure_Inference_SISG_Module17_2019.pdf)
    - [Relatedness inference](https://www.biostat.washington.edu/sites/default/files/modules/Relatedness_Inference_SISG_Module17_2019.pdf)
    - [R packages for PCA and relatedness](https://www.biostat.washington.edu/sites/default/files/modules/R_kinship_pca_0.pdf)
    - [Exercises](https://uw-gac.github.io/SISG_2019/computing-a-grm.html)
- [Mixed model association testing](https://www.biostat.washington.edu/sites/default/files/modules/Mixed_Model_Association_SISG_Module17_2019.pdf)
    - [Exercises](https://uw-gac.github.io/SISG_2019/mixed-models.html)
- [Variant annotation](https://www.biostat.washington.edu/sites/default/files/modules/variant_annotaion_m17_2019.pdf)

**Friday, July 26**

- [Variant annotation](https://www.biostat.washington.edu/sites/default/files/modules/variant_annotaion_m17_2019.pdf)
    - [Exercises](https://uw-gac.github.io/SISG_2019/variant-annotation.html)
- [Analysis pipeline on the cloud](https://www.biostat.washington.edu/sites/default/files/modules/Cloud_Computing_0.pdf)
- Cloud platforms
    - [Analysis Commons](https://www.biostat.washington.edu/sites/default/files/modules/AnalysisCommons_Brody_2019.pdf)
    - [Seven Bridges](https://www.biostat.washington.edu/sites/default/files/modules/SISG19_Scaling_WGS_Association_Studies_in_the_Cloud_with_Seven_Bridges.pdf) (Part 2)
    - [Terra](https://www.biostat.washington.edu/sites/default/files/modules/Terra_Overview_2019-07-02_SISG.pdf) ([Account instructions](https://www.biostat.washington.edu/sites/default/files/modules/Terra_Instructions_SISG.pdf))

Download the workshop data and exercises: https://github.com/UW-GAC/SISG_2019/archive/master.zip

## R packages used

- [SeqArray](http://bioconductor.org/packages/release/bioc/html/SeqArray.html)
- [SeqVarTools](http://bioconductor.org/packages/release/bioc/html/SeqVarTools.html)
- [GENESIS](http://bioconductor.org/packages/release/bioc/html/GENESIS.html)
- [SNPRelate](http://bioconductor.org/packages/release/bioc/html/SNPRelate.html)
- [TopmedPipeline](https://github.com/UW-GAC/analysis_pipeline/tree/master/TopmedPipeline)
- [wgsaparsr](https://github.com/UW-GAC/wgsaparsr)
- [tidyverse](https://www.tidyverse.org)
- [GGally](https://cran.r-project.org/web/packages/GGally)
    

## Resources

If you are new to R, you might find the following material helpful:

- [Introduction to R](http://faculty.washington.edu/kenrice/rintro/indexSEA15.shtml) materials from SISG Module 3
- [Graphics with ggplot2](http://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html) tutorial
- Data manipulation with [dplyr](http://dplyr.tidyverse.org/)
